### ISSUE TITLE
Lack of documentation. How to get started with Django.

### ISSUE THREAD

**Issue by ramusus** [maxtepkeev/architect#16]
I just create model

```
@architect.install('partition', type='range', subtype='date', constraint='month', column='date_from')
class GroupUserActivity(models.Model):
    date_from = models.DateField()
    date_to = models.DateField()
    period = models.PositiveSmallIntegerField(db_index=True)
```

and put into the table dataset with different months in date_from column. And I don't see any difference in database comparing to using without architect.

What should I do to create triggers all other staff for handling child tables automatically 

Database - Postgres 9.1, 
Django 1.5.4

**Comment by maxtepkeev** [comment]
Hi,

Are you sure you have read the [docs](http://architect.readthedocs.org/features/partition/index.html), because it's all there, you missed several steps from the docs that is why you don't see any difference in  your database structure.

Here is a summary:

1) Create a Django model and run ``syncdb`` to create the table in the database
2) Add ``architect.install`` decorator to the model
3) Run the following command ``export DJANGO_SETTINGS_MODULE=mysite.settings`` where mysite.settings is your settings module
4) Finally, run the following command ``architect partition --module path.to.the.model.module`` that will create the needed triggers in the database

That's it

**Comment by ramusus** [comment]
Thanks! I just figured out that.
