### ISSUE TITLE
Unable to initialize architect using Django

### ISSUE THREAD

**Issue by faxioman** [maxtepkeev/architect#2]
Hi.
I'm not able to initialize architect using Django
I'm trying using:

architect partition --module mdata.models

where mdata is my app and models the module with my partitioned model.
I'm using virtualenv and my current path is where "mdata" exists.

**Comment by pajooh** [comment]
@maxtepkeev could you tag a new version (```0.2.1```?) containing the fix of this bug please?
where using ```pip```, it's better to tag frequently to keep everyone up to date

**Comment by maxtepkeev** [comment]
@pajooh Yeah, I know. The problem is that there are several other important bugs that should be fixed before the next release will be possible. I didn't have a time for this project until now, now I'm in the process of rewriting some parts of it and fixing the bugs, so expect a new release in the next few weeks.

**Comment by maxtepkeev** [comment]
Fixed in v0.3.0. Please see docs, because Architect was almost completely rewritten.

@gotlium I didn't completely get what your comment was about. If it is still relevant, please open a new issue with detailed description of the problem.
