### ISSUE TITLE
Database inspection support

### ISSUE THREAD

**Issue by azmeuk** [maxtepkeev/architect#31]
Hi.
I would like to work with an existing partitioned database. I thought that I would need `architect` to deal with the partitioning, and I would like to use the django `inspectdb` command to retrieve the database models. Is there any support for this command with architect? I could not find any documentation about it. If no, is there any plans to support it?

Thanks for your help.

**Comment by maxtepkeev** [comment]
Hi,

What database do you have (mysql/postgres) ? How are tables partitioned (is it something that architect already supports, e.g. by date ? How are new partitions created, e.g. by hand/triggers/cron ?

**Comment by azmeuk** [comment]
This is a MySQL database, tables are partitioned with integers (e.g. foobar1, foobar2 etc.), that have been created with a CakePHP v 0.2.9. With your last question I see that I lack a bit of database partitioning knowledge. Partitioning isn't handled by the sql server?

**Comment by maxtepkeev** [comment]
I don't really understand from your description what foobar1, foobar2 and so on mean ? What are the partitioning rules for records stored inside foobar1 and inside foobar2, what about foobar3 and so on ?

Currently architect only supports partitioning by date (see [docs](http://architect.readthedocs.io/features/partition/mysql.html#date)) for MySQL, so I don't think you will be able to use it with your current partitions because from what you've described it doesn't seem that you're using partitioning by date.

**Comment by azmeuk** [comment]
You are right. There seems to be nothing related with dates with the partitioning I struggle with. I think we can close the question.
